name: Build

on:
    push:
        tags:
            - "*" # Triggers on any tag

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  version: 10
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: Build App
              run: pnpm build

            # Optional: upload build artifacts
            - name: Upload build
              uses: actions/upload-artifact@v4
              # Unexpected error fetching GitHub release for tag refs/tags/v1.0.0: HttpError: Resource not accessible by integration
              # Error: Resource not accessible by integration. Maybe i need to create the secret?
              with:
                  name: svelte-build
                  path: dist/ # Adjust if your output dir is different (e.g., `dist/`)

            - name: Zip the build
              run: |
                  mkdir -p release
                  zip -r release/rem-to-px.zip dist/

            - name: Upload zip to release
              uses: softprops/action-gh-release@v1
              with:
                  files: release/rem-to-px.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
